"""Domain rules, seniority tiers, salary scales, and regex patterns for filtering and scoring."""

from __future__ import annotations

# Default scoring rules used only when a user profile has no `scoring_rules`
# set in Supabase yet (see engine/scoring.py: get_scoring_rules). Domain and
# seniority rules are candidate-specific, so they live entirely on each
# user's profile (editable in the Profile UI) rather than hardcoded here.
# scoring.py already falls back to sane neutral defaults (mid-level seniority,
# neutral domain score) when these lists are empty.
DEFAULT_NEGATIVE_DOMAINS: list[dict] = []
DEFAULT_POSITIVE_DOMAINS: list[dict] = []
DEFAULT_SENIORITY_TIERS: list[dict] = []
DEFAULT_DISQUALIFIERS: list[str] = []

DEFAULT_SCORING_WEIGHTS: dict[str, float | int] = {
    "domain": 25,
    "semantic": 25,
    "competency": 20,
    "seniority": 15,
    "salary": 15,
    "contract": 10,
    "target_role_bonus": 6,
    "location_bonus": 4,
    "work_mode_bonus": 2,
    "fixed_term_penalty": 8,
    "disqualification_cap": 10,
}

DEFAULT_SCORING_RULES: dict = {
    "negative_domains": DEFAULT_NEGATIVE_DOMAINS,
    "positive_domains": DEFAULT_POSITIVE_DOMAINS,
    "seniority_tiers": DEFAULT_SENIORITY_TIERS,
    "disqualifiers": DEFAULT_DISQUALIFIERS,
    "weights": DEFAULT_SCORING_WEIGHTS,
}


GENERIC_NON_JOB_TITLES: set[str] = {
    "english",
    "irish",
    "gaeilge",
    "french",
    "german",
    "spanish",
    "francais",
    "deutsch",
    "espanol",
    "state boards",
    "medical consultants",
    "vacancies",
    "current vacancies",
    "all vacancies",
    "join our team",
    "join us",
    "work with us",
    "work for us",
    "working with us",
    "our team",
    "next page",
    "previous page",
    "next jobs",
    "previous jobs",
    "next",
    "previous",
    "clear",
    "view saved jobs",
    "saved jobs",
    "recruitment events",
    "events",
    "leadership",
    "programming",
    "london",
    "madrid",
    "malaga",
    "malta",
    "porto",
    "portugal",
    "prestwick",
    "spain",
    "united kingdom",
    "shannon",
    "northern ireland",
    "ireland",
    "dublin",
    "cork",
    "galway",
    "limerick",
    "waterford",
    "kildare",
    "meath",
    "wicklow",
    "belfast",
    "birmingham",
    "barcelona",
    "girona",
    "apply now",
    "apply",
    "apply here",
    "apply online",
    "quick apply",
    "see jobs",
    "view jobs",
    "see all jobs",
    "view all jobs",
    "all jobs",
    "search jobs",
    "search all jobs",
    "search opportunities",
    "explore opportunities",
    "skip to content",
    "skip to main content",
    "jump to content",
    "jump to main content",
    "skip to navigation",
    "back to top",
    "back to jobs",
    "back to search",
    "register for job alerts",
    "job alerts",
    "get job alerts",
    "create job alert",
    "join our talent network",
    "join our talent community",
    "join talent community",
    "sign in",
    "log in",
    "login",
    "register",
    "create account",
    "cookie policy",
    "privacy policy",
    "terms of use",
    "terms & conditions",
    "read more",
    "learn more",
    "find out more",
    "click here",
    "view details",
    "share this job",
    "save job",
    "email this job",
    "print job",
    "download pdf",
    "view saved jobs 0",
    "hospitality & recreation",
    "systems & finance",
    "emergency response",
    "heavy maintenance",
    "engineering",
    "line maintenance",
    "ground handling",
    "ground operations",
    "cabin crew",
    "filter your results",
    "filter results",
    "early careers",
    "early career",
    "go to next page",
    "go to last page",
    "go to previous page",
    "go to page",
}

ALLOWED_SINGLE_WORD_JOBS: set[str] = {
    "accountant",
    "administrator",
    "architect",
    "auditor",
    "barista",
    "biochemist",
    "biologist",
    "buyer",
    "carpenter",
    "chef",
    "chemist",
    "consultant",
    "controller",
    "cook",
    "counsel",
    "caretaker",
    "dietitian",
    "director",
    "doctor",
    "driver",
    "economist",
    "electrician",
    "engineer",
    "executive",
    "mechanic",
    "manager",
    "nurse",
    "officer",
    "optometrist",
    "paralegal",
    "pharmacist",
    "physician",
    "physiotherapist",
    "planner",
    "plumber",
    "principal",
    "professor",
    "programmer",
    "psychologist",
    "receptionist",
    "recruiter",
    "scientist",
    "secretary",
    "specialist",
    "statistician",
    "supervisor",
    "surgeon",
    "surveyor",
    "technician",
    "technologist",
    "trader",
    "writer",
}

NON_IRELAND_PATTERNS: list[str] = [
    r"\b(?:poland|polska|krakow|kraków|warsaw|warszawa|lodz|łódź|wrocław|poznan|gdansk)\b",
    r"\b(?:india|telangana|karnataka|maharashtra|hyderabad|bangalore|bengaluru|mumbai|gurgaon|pune|noida|delhi|chennai)\b",
    r"\b(?:united\s+states|usa|u\.s\.a\.|us-[a-z]{2}\b|in-[a-z]{2}\b|arden hills|maple grove|albany\b.*us-ny|brooklyn park|minnesota|san\s+francisco|chicago|austin|seattle|taylorsville|west haven|phoenix|clovis|twin falls|sharonville|downers grove|mooresville|springfield|gooding|st\.?\s*johns|brookings|halethorpe|towson|maryland)\b",
    r"(?:,\s*|\b)(?:al|ak|az|ar|ca|co|ct|de|fl|ga|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|oh|ok|or|pa|ri|sc|sd|tn|tx|ut|vt|va|wa|wv|wi|wy)\s*(?:\||\b|$)",
    r"\b(?:portsmouth|reading|aberdeen|inverness|stirling|glasgow|scotland|perthshire|renfrewshire|berkshire|windsor|merseyside|uxbridge|leicester|lutterworth|stockport|altrincham|basingstoke|aldershot|andover|oxford|melksham|swindon)\b",
    r"\b(?:barcelona|madrid|paris|granby\s*,\s*qc|quebec|canada|toronto|vancouver|mississauga|copenhagen|aalborg)\b",
    r"\b(?:saudi\s+arabia|singapore|australia|sydney|melbourne)\b",
    r"\b(?:süddeutschland|österreich|deutschland|germany|austria)\b",
    r"\b(?:rome|roma)\b.*italy",
]

# Canonical display names for known Irish (and Northern Irish) cities/towns,
# used to normalize scraped location text into a consistent "City, Country"
# display format rather than showing raw/garbage strings verbatim.
IRISH_CITY_DISPLAY_NAMES: list[str] = [
    "Dublin",
    "Cork",
    "Galway",
    "Limerick",
    "Waterford",
    "Kilkenny",
    "Drogheda",
    "Dundalk",
    "Sligo",
    "Athlone",
    "Kildare",
    "Maynooth",
    "Naas",
    "Leixlip",
    "Newbridge",
    "Navan",
    "Wicklow",
    "Bray",
    "Greystones",
    "Arklow",
    "Tralee",
    "Killarney",
    "Letterkenny",
    "Ennis",
    "Carlow",
    "Clonmel",
    "Wexford",
    "Mullingar",
    "Portlaoise",
    "Tullamore",
    "Cavan",
    "Monaghan",
    "Castlebar",
    "Shannon",
    "Ringaskiddy",
    "Leixlip",
    "Grange Castle",
]

NORTHERN_IRELAND_CITY_DISPLAY_NAMES: list[str] = ["Belfast", "Derry", "Antrim", "Armagh"]

SPECIFIC_IRISH_PLACES: list[str] = [
    r"\b(?:dublin|cork|galway|limerick|waterford|kilkenny|drogheda|dundalk|sligo|athlone)\b",
    r"\b(?:kildare|maynooth|naas|leixlip|newbridge|meath|navan|wicklow|bray|greystones|arklow)\b",
    r"\b(?:louth|kerry|tralee|killarney|donegal|letterkenny|clare|ennis|carlow|tipperary|clonmel)\b",
    r"\b(?:wexford|westmeath|mullingar|laois|portlaoise|offaly|tullamore|cavan|monaghan)\b",
    r"\b(?:leitrim|roscommon|longford|mayo|castlebar)\b",
    r"\b(?:belfast|derry|antrim|down|armagh|fermanagh|tyrone)\b",
]

ERROR_ANTI_BOT_PATTERNS: list[str] = [
    r"javascript is disabled",
    r"verify (?:that )?you'?re not a robot",
    r"verify you are (?:a )?human",
    r"checking your browser before accessing",
    r"cloudflare ray id",
    r"cf-browser-verification",
    r"ddos protection by cloudflare",
    r"access denied",
    r"403 forbidden",
    r"404 not found",
    r"enable javascript",
    r"turn javascript on",
    r"incapsula",
    r"perimeterx",
    r"security check",
    r"attention required! \| cloudflare",
    r"this site is currently unavailable",
    r"internal server error",
]
