-- ==============================================================================
-- JobPulse Unified Database Schema (Baseline Initial Migration)
-- Target Database: PostgreSQL 17 / Supabase
-- ==============================================================================

-- Enable required PostgreSQL extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ==============================================================================
-- 1. AUTHORIZED USERS
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.authorized_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'admin',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT check_authorized_users_email_lowercase CHECK (email = lower(email))
);

-- Seed initial default authorized admin
INSERT INTO public.authorized_users (email, role)
VALUES ('admin@example.com', 'admin')
ON CONFLICT (email) DO NOTHING;

-- Helper function: Check if current authenticated caller is authorized
CREATE OR REPLACE FUNCTION public.is_authorized_user()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.authorized_users
    WHERE lower(email) = lower(auth.jwt() ->> 'email')
  );
$$;

-- ==============================================================================
-- 2. JOBS TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    location TEXT NOT NULL DEFAULT 'Not specified',
    employment_type TEXT NOT NULL DEFAULT 'Not specified',
    salary_text TEXT,
    description TEXT NOT NULL,
    url TEXT NOT NULL,
    source TEXT NOT NULL,
    relevance INTEGER NOT NULL DEFAULT 0,
    matched_skills JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL DEFAULT 'new',
    first_seen_at TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ DEFAULT NOW(),
    fit_tier TEXT DEFAULT 'Unassessed',
    role_domain TEXT DEFAULT 'General',
    seniority_level TEXT DEFAULT 'Not specified',
    ai_analysis JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_jobs_status ON public.jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_relevance ON public.jobs(relevance DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_domain ON public.jobs(role_domain);
CREATE INDEX IF NOT EXISTS idx_jobs_company ON public.jobs(company);
CREATE INDEX IF NOT EXISTS idx_jobs_location ON public.jobs(location);
CREATE INDEX IF NOT EXISTS idx_jobs_last_seen_at ON public.jobs(last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_title_trgm ON public.jobs USING gin (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_jobs_company_trgm ON public.jobs USING gin (company gin_trgm_ops);

-- ==============================================================================
-- 3. SOURCES TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    url TEXT NOT NULL,
    mode TEXT NOT NULL DEFAULT 'company crawler',
    last_status TEXT NOT NULL DEFAULT 'Not synced',
    last_synced_at TIMESTAMPTZ,
    detail TEXT,
    opportunities_found INTEGER DEFAULT 0
);

-- ==============================================================================
-- 4. EMPLOYERS TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.employers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    sector TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 1,
    careers_url TEXT NOT NULL,
    discovered_jobs_url TEXT,
    last_scraped_at TIMESTAMPTZ,
    status TEXT DEFAULT 'pending',
    opportunities_found INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_employers_sector ON public.employers(sector);
CREATE INDEX IF NOT EXISTS idx_employers_priority ON public.employers(priority);

-- ==============================================================================
-- 5. USER PROFILES TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL DEFAULT '',
    first_name TEXT DEFAULT '',
    last_name TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    phone_country_code TEXT DEFAULT '+353',
    linkedin_url TEXT DEFAULT '',
    work_authorization TEXT DEFAULT 'EU Citizen',
    gender TEXT DEFAULT '',
    headline TEXT NOT NULL DEFAULT '',
    "current_role" TEXT NOT NULL DEFAULT '',
    current_company TEXT DEFAULT '',
    years_of_experience TEXT DEFAULT '10+ years',
    location TEXT NOT NULL DEFAULT '',
    target_roles TEXT[] DEFAULT '{}',
    target_locations TEXT[] DEFAULT '{}',
    work_mode TEXT DEFAULT 'Hybrid',
    work_modes TEXT[] DEFAULT '{Hybrid,Remote,On-site}',
    minimum_salary INTEGER NOT NULL DEFAULT 50000,
    salary_min INTEGER DEFAULT 50000,
    employment TEXT NOT NULL DEFAULT 'Permanent only',
    education TEXT NOT NULL DEFAULT '',
    certifications TEXT DEFAULT '',
    experience_level TEXT DEFAULT '',
    highest_education TEXT DEFAULT 'Master''s Degree (QQI Level 9)',
    education_details TEXT DEFAULT '',
    languages TEXT[] DEFAULT '{}',
    tools_software TEXT[] DEFAULT '{}',
    summary TEXT NOT NULL DEFAULT '',
    keywords TEXT[] DEFAULT '{}',
    avatar_url TEXT DEFAULT '',
    scoring_rules JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT check_user_profiles_email_lowercase CHECK (user_email = lower(user_email))
);

CREATE INDEX IF NOT EXISTS idx_user_profiles_user_email ON public.user_profiles(user_email);

-- ==============================================================================
-- 6. APPLICATION DOCUMENTS (MULTIPLE CVS & COVER LETTERS)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_cvs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_size INTEGER NOT NULL DEFAULT 0,
    mime_type TEXT NOT NULL DEFAULT 'application/pdf',
    file_data TEXT,
    storage_path TEXT,
    description TEXT,
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT check_user_cvs_email_lowercase CHECK (user_email = lower(user_email))
);

CREATE INDEX IF NOT EXISTS idx_user_cvs_user_email ON public.user_cvs(user_email);

CREATE TABLE IF NOT EXISTS public.user_cover_letters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_size INTEGER NOT NULL DEFAULT 0,
    mime_type TEXT NOT NULL DEFAULT 'application/pdf',
    file_data TEXT,
    storage_path TEXT,
    description TEXT,
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT check_user_cover_letters_email_lowercase CHECK (user_email = lower(user_email))
);

CREATE INDEX IF NOT EXISTS idx_user_cover_letters_user_email ON public.user_cover_letters(user_email);

-- Document limits trigger (max 10 CVs, max 10 Cover Letters per tenant)
CREATE OR REPLACE FUNCTION public.check_user_cv_limit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF (SELECT COUNT(*) FROM public.user_cvs WHERE lower(user_email) = lower(NEW.user_email)) >= 10 THEN
    RAISE EXCEPTION 'Maximum document limit of 10 CVs reached. Please delete an existing CV before uploading a new one.';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_check_user_cv_limit ON public.user_cvs;
CREATE TRIGGER trg_check_user_cv_limit
  BEFORE INSERT ON public.user_cvs
  FOR EACH ROW
  EXECUTE FUNCTION public.check_user_cv_limit();

CREATE OR REPLACE FUNCTION public.check_user_cover_letter_limit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF (SELECT COUNT(*) FROM public.user_cover_letters WHERE lower(user_email) = lower(NEW.user_email)) >= 10 THEN
    RAISE EXCEPTION 'Maximum document limit of 10 cover letters reached. Please delete an existing cover letter before uploading a new one.';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_check_user_cover_letter_limit ON public.user_cover_letters;
CREATE TRIGGER trg_check_user_cover_letter_limit
  BEFORE INSERT ON public.user_cover_letters
  FOR EACH ROW
  EXECUTE FUNCTION public.check_user_cover_letter_limit();

-- ==============================================================================
-- 7. USER-SPECIFIC JOB STATUSES & EVALUATIONS
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_job_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'new',
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_email, job_id),
    CONSTRAINT check_user_job_statuses_email_lowercase CHECK (user_email = lower(user_email))
);

CREATE INDEX IF NOT EXISTS idx_user_job_statuses_user_email ON public.user_job_statuses(user_email);
CREATE INDEX IF NOT EXISTS idx_user_job_statuses_job_id ON public.user_job_statuses(job_id);

CREATE TABLE IF NOT EXISTS public.user_job_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
    relevance INTEGER NOT NULL DEFAULT 0,
    fit_tier TEXT,
    matched_skills JSONB NOT NULL DEFAULT '[]'::jsonb,
    ai_analysis JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_email, job_id),
    CONSTRAINT check_user_job_evaluations_email_lowercase CHECK (user_email = lower(user_email))
);

CREATE INDEX IF NOT EXISTS idx_user_job_evaluations_user_email ON public.user_job_evaluations(user_email);
CREATE INDEX IF NOT EXISTS idx_user_job_evaluations_job_id ON public.user_job_evaluations(job_id);
CREATE INDEX IF NOT EXISTS idx_user_job_evaluations_relevance ON public.user_job_evaluations(relevance DESC);

-- ==============================================================================
-- 8. ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.authorized_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_cvs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_cover_letters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_job_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_job_evaluations ENABLE ROW LEVEL SECURITY;

-- 8.1 Authorized Users
CREATE POLICY "Users can only check own authorization"
  ON public.authorized_users FOR SELECT
  TO authenticated
  USING (lower(email) = lower(auth.jwt() ->> 'email'));

-- 8.2 Shared Catalog (Jobs, Sources, Employers)
CREATE POLICY "Authorized users can read jobs"
  ON public.jobs FOR SELECT
  TO authenticated
  USING (public.is_authorized_user());

CREATE POLICY "Service role full access on jobs"
  ON public.jobs FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authorized users can read sources"
  ON public.sources FOR SELECT
  TO authenticated
  USING (public.is_authorized_user());

CREATE POLICY "Service role full access on sources"
  ON public.sources FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authorized users can read employers"
  ON public.employers FOR SELECT
  TO authenticated
  USING (public.is_authorized_user());

CREATE POLICY "Service role full access on employers"
  ON public.employers FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- 8.3 User Profiles
CREATE POLICY "Users can read own profile"
  ON public.user_profiles FOR SELECT
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can insert own profile"
  ON public.user_profiles FOR INSERT
  TO authenticated
  WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can update own profile"
  ON public.user_profiles FOR UPDATE
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user())
  WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can delete own profile"
  ON public.user_profiles FOR DELETE
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

-- 8.4 User CVs
CREATE POLICY "Users can read own cvs"
  ON public.user_cvs FOR SELECT
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can insert own cvs"
  ON public.user_cvs FOR INSERT
  TO authenticated
  WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can update own cvs"
  ON public.user_cvs FOR UPDATE
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user())
  WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can delete own cvs"
  ON public.user_cvs FOR DELETE
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

-- 8.5 User Cover Letters
CREATE POLICY "Users can read own cover letters"
  ON public.user_cover_letters FOR SELECT
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can insert own cover letters"
  ON public.user_cover_letters FOR INSERT
  TO authenticated
  WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can update own cover letters"
  ON public.user_cover_letters FOR UPDATE
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user())
  WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can delete own cover letters"
  ON public.user_cover_letters FOR DELETE
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

-- 8.6 User Job Statuses
CREATE POLICY "Users can read own job statuses"
  ON public.user_job_statuses FOR SELECT
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can insert own job statuses"
  ON public.user_job_statuses FOR INSERT
  TO authenticated
  WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can update own job statuses"
  ON public.user_job_statuses FOR UPDATE
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user())
  WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can delete own job statuses"
  ON public.user_job_statuses FOR DELETE
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

-- 8.7 User Job Evaluations
CREATE POLICY "Users can read own evaluations"
  ON public.user_job_evaluations FOR SELECT
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can insert own evaluations"
  ON public.user_job_evaluations FOR INSERT
  TO authenticated
  WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can update own evaluations"
  ON public.user_job_evaluations FOR UPDATE
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user())
  WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

CREATE POLICY "Users can delete own evaluations"
  ON public.user_job_evaluations FOR DELETE
  TO authenticated
  USING (lower(user_email) = lower(auth.jwt() ->> 'email') AND public.is_authorized_user());

-- Service role bypass for backend integrations
CREATE POLICY "Service role full access on user_profiles" ON public.user_profiles FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on user_cvs" ON public.user_cvs FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on user_cover_letters" ON public.user_cover_letters FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on user_job_statuses" ON public.user_job_statuses FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on user_job_evaluations" ON public.user_job_evaluations FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ==============================================================================
-- 9. STORAGE BUCKET POLICIES (user-documents)
-- ==============================================================================
DO $$
BEGIN
  UPDATE storage.buckets
  SET file_size_limit = 10485760, -- 10MB
      allowed_mime_types = ARRAY[
        'application/pdf',
        'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'text/plain'
      ]
  WHERE id = 'user-documents';
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DROP POLICY IF EXISTS "Users can only view own storage documents" ON storage.objects;
DROP POLICY IF EXISTS "Users can only upload own storage documents" ON storage.objects;
DROP POLICY IF EXISTS "Users can only update own storage documents" ON storage.objects;
DROP POLICY IF EXISTS "Users can only delete own storage documents" ON storage.objects;

CREATE POLICY "Users can only view own storage documents"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'user-documents'
  AND public.is_authorized_user()
  AND lower(split_part(name, '/', 1)) = lower(auth.jwt() ->> 'email')
);

CREATE POLICY "Users can only upload own storage documents"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'user-documents'
  AND public.is_authorized_user()
  AND lower(split_part(name, '/', 1)) = lower(auth.jwt() ->> 'email')
);

CREATE POLICY "Users can only update own storage documents"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'user-documents'
  AND public.is_authorized_user()
  AND lower(split_part(name, '/', 1)) = lower(auth.jwt() ->> 'email')
)
WITH CHECK (
  bucket_id = 'user-documents'
  AND public.is_authorized_user()
  AND lower(split_part(name, '/', 1)) = lower(auth.jwt() ->> 'email')
);

CREATE POLICY "Users can only delete own storage documents"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'user-documents'
  AND public.is_authorized_user()
  AND lower(split_part(name, '/', 1)) = lower(auth.jwt() ->> 'email')
);

-- ==============================================================================
-- 10. REALTIME CONFIGURATION
-- Only public jobs table is published. Private tenant tables are excluded.
-- ==============================================================================
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.jobs;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;

  BEGIN
    ALTER PUBLICATION supabase_realtime DROP TABLE public.user_profiles;
  EXCEPTION WHEN undefined_object THEN NULL;
  END;

  BEGIN
    ALTER PUBLICATION supabase_realtime DROP TABLE public.user_job_statuses;
  EXCEPTION WHEN undefined_object THEN NULL;
  END;
END $$;

-- ==============================================================================
-- 11. RPC STORED PROCEDURES
-- ==============================================================================

-- 11.1 get_overview_metrics
CREATE OR REPLACE FUNCTION public.get_overview_metrics(p_user_email TEXT DEFAULT NULL)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_caller_email TEXT;
    result JSONB;
BEGIN
    IF NOT public.is_authorized_user() THEN
        RAISE EXCEPTION 'Access denied. Caller is not authorized.';
    END IF;

    v_caller_email := lower(auth.jwt() ->> 'email');
    IF p_user_email IS NOT NULL AND lower(p_user_email) <> v_caller_email THEN
        RAISE EXCEPTION 'Access denied. You can only request metrics for your own profile.';
    END IF;

    WITH user_evals AS (
        SELECT job_id, relevance, matched_skills
        FROM public.user_job_evaluations
        WHERE lower(user_email) = v_caller_email
    ),
    user_stats AS (
        SELECT job_id, status
        FROM public.user_job_statuses
        WHERE lower(user_email) = v_caller_email
    ),
    combined AS (
        SELECT 
            j.id,
            COALESCE(e.relevance, j.relevance, 0) AS relevance,
            COALESCE(s.status, j.status, 'new') AS status,
            COALESCE(NULLIF(TRIM(j.role_domain), ''), 'General') AS role_domain,
            COALESCE(e.matched_skills, j.matched_skills, '[]'::jsonb) AS matched_skills
        FROM public.jobs j
        LEFT JOIN user_evals e ON e.job_id = j.id
        LEFT JOIN user_stats s ON s.job_id = j.id
    )
    SELECT jsonb_build_object(
        'total', (SELECT count(*) FROM combined),
        'high_fit', (SELECT count(*) FROM combined WHERE relevance >= 75),
        'counts', (
            SELECT COALESCE(jsonb_object_agg(status, cnt), '{}'::jsonb)
            FROM (
                SELECT status, count(*) AS cnt
                FROM combined
                GROUP BY status
            ) st
        ),
        'categories', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object('name', role_domain, 'value', cnt, 'avgMatch', round(avg_rel))), '[]'::jsonb)
            FROM (
                SELECT role_domain, count(*) AS cnt, avg(relevance) AS avg_rel
                FROM combined
                GROUP BY role_domain
                ORDER BY cnt DESC
            ) cat
        ),
        'relevance_distribution', (
            SELECT jsonb_build_array(
                jsonb_build_object('range', '90-100%', 'min', 90, 'max', 100, 'count', count(*) FILTER (WHERE relevance >= 90 AND relevance <= 100)),
                jsonb_build_object('range', '80-89%', 'min', 80, 'max', 89, 'count', count(*) FILTER (WHERE relevance >= 80 AND relevance < 90)),
                jsonb_build_object('range', '70-79%', 'min', 70, 'max', 79, 'count', count(*) FILTER (WHERE relevance >= 70 AND relevance < 80)),
                jsonb_build_object('range', '60-69%', 'min', 60, 'max', 69, 'count', count(*) FILTER (WHERE relevance >= 60 AND relevance < 70)),
                jsonb_build_object('range', '<60%', 'min', 0, 'max', 59, 'count', count(*) FILTER (WHERE relevance < 60))
            )
            FROM combined
        ),
        'top_skills', (
            SELECT COALESCE(jsonb_agg(jsonb_build_object('skill', skill, 'count', cnt, 'percentage', round((cnt::numeric / GREATEST((SELECT count(*) FROM combined)::numeric, 1)) * 100))), '[]'::jsonb)
            FROM (
                SELECT trim(both '"' from elem::text) AS skill, count(*) AS cnt
                FROM combined, jsonb_array_elements(
                    CASE 
                        WHEN jsonb_typeof(matched_skills) = 'array' THEN matched_skills 
                        ELSE '[]'::jsonb 
                    END
                ) AS elem
                WHERE elem::text <> '""'
                GROUP BY skill
                ORDER BY cnt DESC
                LIMIT 6
            ) sk
        )
    ) INTO result;

    RETURN result;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.get_overview_metrics(TEXT) FROM anon, PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_overview_metrics(TEXT) TO authenticated, service_role;

-- 11.2 get_jobs_page
CREATE OR REPLACE FUNCTION public.get_jobs_page(
    p_user_email TEXT DEFAULT NULL,
    p_status TEXT DEFAULT 'all',
    p_domain TEXT DEFAULT 'all',
    p_min_match INTEGER DEFAULT 0,
    p_location TEXT DEFAULT 'all',
    p_salary TEXT DEFAULT 'all',
    p_search TEXT DEFAULT NULL,
    p_sort_by TEXT DEFAULT 'match',
    p_sort_dir TEXT DEFAULT 'desc',
    p_limit INTEGER DEFAULT 40,
    p_offset INTEGER DEFAULT 0
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_caller_email TEXT;
    v_total BIGINT;
    v_items JSONB;
BEGIN
    IF NOT public.is_authorized_user() THEN
        RAISE EXCEPTION 'Access denied. Caller is not authorized.';
    END IF;

    v_caller_email := lower(auth.jwt() ->> 'email');
    IF p_user_email IS NOT NULL AND lower(p_user_email) <> v_caller_email THEN
        RAISE EXCEPTION 'Access denied. You can only query jobs for your own profile.';
    END IF;

    WITH user_evals AS (
        SELECT job_id, relevance, fit_tier, matched_skills
        FROM public.user_job_evaluations
        WHERE lower(user_email) = v_caller_email
    ),
    user_stats AS (
        SELECT job_id, status
        FROM public.user_job_statuses
        WHERE lower(user_email) = v_caller_email
    ),
    combined AS (
        SELECT 
            j.id,
            j.title,
            j.company,
            j.location,
            j.employment_type,
            j.salary_text,
            j.url,
            j.source,
            COALESCE(NULLIF(TRIM(j.role_domain), ''), 'General') AS role_domain,
            j.seniority_level,
            j.last_seen_at,
            COALESCE(e.relevance, j.relevance, 0) AS relevance,
            COALESCE(e.fit_tier, j.fit_tier, 'Unassessed') AS fit_tier,
            COALESCE(e.matched_skills, j.matched_skills, '[]'::jsonb) AS matched_skills,
            COALESCE(s.status, j.status, 'new') AS status
        FROM public.jobs j
        LEFT JOIN user_evals e ON e.job_id = j.id
        LEFT JOIN user_stats s ON s.job_id = j.id
    ),
    filtered AS (
        SELECT *
        FROM combined c
        WHERE 
            (p_status IS NULL OR p_status = 'all' OR c.status = p_status)
            AND (p_domain IS NULL OR p_domain = 'all' OR c.role_domain = p_domain)
            AND (p_min_match IS NULL OR p_min_match <= 0 OR c.relevance >= p_min_match)
            AND (
                p_search IS NULL OR trim(p_search) = '' OR
                (
                    c.title ILIKE '%' || trim(p_search) || '%' OR
                    c.company ILIKE '%' || trim(p_search) || '%' OR
                    c.location ILIKE '%' || trim(p_search) || '%' OR
                    c.matched_skills::text ILIKE '%' || trim(p_search) || '%'
                )
            )
            AND (
                p_location IS NULL OR p_location = 'all' OR
                c.location ILIKE '%' || trim(p_location) || '%'
            )
            AND (
                p_salary IS NULL OR p_salary = 'all' OR
                (
                    CASE
                        WHEN p_salary = 'disclosed' THEN c.salary_text IS NOT NULL AND trim(c.salary_text) <> ''
                        WHEN p_salary = '50k' THEN (c.salary_text ~* '([5-9][0-9]|[1-9][0-9]{2}),[0-9]{3}|[5-9][0-9]k')
                        WHEN p_salary = '60k' THEN (c.salary_text ~* '([6-9][0-9]|[1-9][0-9]{2}),[0-9]{3}|[6-9][0-9]k')
                        WHEN p_salary = '70k' THEN (c.salary_text ~* '([7-9][0-9]|[1-9][0-9]{2}),[0-9]{3}|[7-9][0-9]k')
                        WHEN p_salary = '80k' THEN (c.salary_text ~* '([8-9][0-9]|[1-9][0-9]{2}),[0-9]{3}|[8-9][0-9]k')
                        ELSE TRUE
                    END
                )
            )
    )
    SELECT 
        (SELECT count(*) FROM filtered),
        COALESCE(
            (
                SELECT jsonb_agg(row_to_json(r))
                FROM (
                    SELECT * FROM filtered
                    ORDER BY 
                        CASE WHEN p_sort_by = 'match' AND p_sort_dir = 'asc' THEN relevance END ASC,
                        CASE WHEN p_sort_by = 'match' AND p_sort_dir <> 'asc' THEN relevance END DESC,
                        CASE WHEN p_sort_by = 'location' AND p_sort_dir = 'desc' THEN location END DESC,
                        CASE WHEN p_sort_by = 'location' AND p_sort_dir <> 'desc' THEN location END ASC,
                        CASE WHEN p_sort_by = 'category' AND p_sort_dir = 'desc' THEN role_domain END DESC,
                        CASE WHEN p_sort_by = 'category' AND p_sort_dir <> 'desc' THEN role_domain END ASC,
                        CASE WHEN p_sort_by = 'salary' AND p_sort_dir = 'asc' THEN salary_text END ASC,
                        CASE WHEN p_sort_by = 'salary' AND p_sort_dir <> 'asc' THEN salary_text END DESC,
                        id DESC
                    LIMIT GREATEST(p_limit, 1)
                    OFFSET GREATEST(p_offset, 0)
                ) r
            ),
            '[]'::jsonb
        )
    INTO v_total, v_items;

    RETURN jsonb_build_object(
        'total', v_total,
        'items', v_items
    );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.get_jobs_page(TEXT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, INTEGER, INTEGER) FROM anon, PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_jobs_page(TEXT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, INTEGER, INTEGER) TO authenticated, service_role;
