-- Forward migration: the crawl-target board catalog.
--
-- One row per (provider, board, region) crawl target: the durable source of
-- truth for what the scraper visits, replacing config/websites.yaml and
-- config/board_seeds.yaml as the runtime list. The row carries only public
-- crawl metadata -- never candidate data -- and is reachable only through the
-- service role.
CREATE TABLE public.boards (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider             text NOT NULL CHECK (provider ~ '^[a-z][a-z0-9_]{0,39}$'),
  board                text NOT NULL CHECK (length(btrim(board)) BETWEEN 1 AND 500),
  region               text NOT NULL DEFAULT '',
  company              text NOT NULL CHECK (length(btrim(company)) BETWEEN 1 AND 500),
  employer_id          bigint REFERENCES public.employers(id) ON DELETE SET NULL,
  careers_url          text NOT NULL CHECK (careers_url ~ '^https?://'),
  sector               text NOT NULL DEFAULT 'General',
  priority             integer NOT NULL DEFAULT 50 CHECK (priority BETWEEN 1 AND 100),
  enabled              boolean NOT NULL DEFAULT true,
  status               text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','rejected','retired')),
  discovery_source     text NOT NULL DEFAULT 'manual',
  metadata             jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  consecutive_failures integer NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0),
  cooldown_until       timestamptz,
  last_error           text,
  last_verified_at     timestamptz,
  last_crawled_at      timestamptz,
  last_ingested_count  integer NOT NULL DEFAULT 0 CHECK (last_ingested_count >= 0),
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.boards IS 'Crawl-target catalog: which company is crawled on which provider/board. Public crawl metadata only; no candidate or owner data.';
COMMENT ON COLUMN public.boards.board IS 'Provider-native board id (slug, tenant/site, subdomain). Non-empty; identity is (provider, lower(board), region).';
COMMENT ON COLUMN public.boards.status IS 'pending = unproven but crawled; active = proven by a successful crawl; rejected = invalid candidate kept for the record; retired = no longer crawled.';
COMMENT ON COLUMN public.boards.discovery_source IS 'Where the row came from: manual, config, seed, harvest, contribution, or discovery.';
COMMENT ON COLUMN public.boards.metadata IS 'Free-form discovery/verification evidence; never candidate data.';

-- Identity mirrors the live crawl set and folds case, like a board catalog.
CREATE UNIQUE INDEX boards_identity_key ON public.boards (provider, lower(board), region)
  WHERE status IN ('pending', 'active');
CREATE INDEX boards_crawlable_idx ON public.boards (provider, priority DESC)
  WHERE enabled AND status IN ('pending', 'active');
CREATE INDEX boards_employer_id_idx ON public.boards (employer_id);
CREATE INDEX boards_company_idx ON public.boards (lower(company));

-- Service-role-only catalog: no browser read path, RLS still enforced.
ALTER TABLE public.boards ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.boards FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.boards TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.boards_id_seq TO service_role;
