-- Crawl operations contain shared source facts only and are inaccessible to browser roles.
CREATE TABLE public.crawl_tasks (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 source_key text NOT NULL UNIQUE CHECK (length(source_key) BETWEEN 1 AND 500),
 target jsonb NOT NULL CHECK (jsonb_typeof(target)='object' AND octet_length(target::text)<=8192),
 priority integer NOT NULL DEFAULT 50 CHECK (priority BETWEEN 0 AND 100),
 status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','running','complete','dead')),
 next_fetch_at timestamptz NOT NULL DEFAULT now(),
 attempt integer NOT NULL DEFAULT 0 CHECK (attempt>=0),
 max_attempts integer NOT NULL DEFAULT 5 CHECK (max_attempts BETWEEN 1 AND 10),
 lease_token uuid,
 lease_until timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK ((status='running')=(lease_token IS NOT NULL AND lease_until IS NOT NULL))
);
CREATE INDEX crawl_tasks_due ON public.crawl_tasks (next_fetch_at,priority DESC,created_at) WHERE status IN ('pending','running');
CREATE TABLE public.crawl_runs (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 task_id uuid NOT NULL REFERENCES public.crawl_tasks(id),
 lease_token uuid NOT NULL UNIQUE,
 attempt integer NOT NULL,
 started_at timestamptz NOT NULL DEFAULT now(),
 finished_at timestamptz,
 status text NOT NULL DEFAULT 'running' CHECK (status IN ('running','complete','incomplete','blocked','expired')),
 result jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(result)='object' AND octet_length(result::text)<=32768)
);
CREATE INDEX crawl_runs_task ON public.crawl_runs(task_id,started_at DESC);
CREATE TABLE public.crawl_snapshots (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 run_id uuid REFERENCES public.crawl_runs(id),
 source_key text NOT NULL CHECK (length(source_key) BETWEEN 1 AND 500),
 url text NOT NULL CHECK (length(url)<=4096),
 http_status integer NOT NULL CHECK (http_status BETWEEN 100 AND 599),
 content_hash text NOT NULL CHECK (content_hash ~ '^[a-f0-9]{64}$'),
 body_key text NOT NULL CHECK (body_key ~ '^[a-f0-9]{64}\.(json|html|bin)$'),
 body_bytes integer NOT NULL CHECK (body_bytes BETWEEN 0 AND 2097152),
 parser_version text NOT NULL,
 fetched_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX crawl_snapshots_source ON public.crawl_snapshots(source_key,fetched_at DESC);
CREATE TABLE public.job_occurrences (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 job_id bigint NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
 source_key text NOT NULL CHECK (length(source_key) BETWEEN 1 AND 500),
 external_id text NOT NULL CHECK (length(external_id) BETWEEN 1 AND 4096),
 source_url text NOT NULL CHECK (length(source_url)<=4096),
 content_hash text NOT NULL CHECK (content_hash ~ '^[a-f0-9]{64}$'),
 first_seen_at timestamptz NOT NULL DEFAULT now(),
 last_seen_at timestamptz NOT NULL DEFAULT now(),
 snapshot_id uuid REFERENCES public.crawl_snapshots(id) ON DELETE SET NULL,
 UNIQUE (source_key,external_id)
);
CREATE INDEX job_occurrences_job ON public.job_occurrences(job_id);
ALTER TABLE public.crawl_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crawl_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crawl_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_occurrences ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.crawl_tasks,public.crawl_runs,public.crawl_snapshots,public.job_occurrences FROM PUBLIC,anon,authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.crawl_tasks,public.crawl_runs,public.crawl_snapshots,public.job_occurrences TO service_role;
GRANT USAGE,SELECT ON SEQUENCE public.job_occurrences_id_seq TO service_role;

CREATE FUNCTION public.enqueue_crawl(p_source_key text,p_target jsonb,p_priority integer DEFAULT 50,p_due timestamptz DEFAULT now())
RETURNS uuid LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog,public AS $$
DECLARE task_id uuid;
BEGIN
 INSERT INTO public.crawl_tasks(source_key,target,priority,next_fetch_at)
 VALUES(p_source_key,p_target,p_priority,p_due)
 ON CONFLICT(source_key) DO UPDATE SET target=EXCLUDED.target,priority=EXCLUDED.priority,
 status=CASE WHEN crawl_tasks.status='running' THEN 'running' ELSE 'pending' END,
 attempt=CASE WHEN crawl_tasks.status='running' THEN crawl_tasks.attempt ELSE 0 END,
 next_fetch_at=CASE WHEN crawl_tasks.status='running' THEN crawl_tasks.next_fetch_at ELSE EXCLUDED.next_fetch_at END,
 updated_at=now() RETURNING id INTO task_id;
 RETURN task_id;
END $$;

CREATE FUNCTION public.claim_crawl(p_lease_seconds integer DEFAULT 120)
RETURNS SETOF public.crawl_tasks LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog,public AS $$
DECLARE task public.crawl_tasks; token uuid;
BEGIN
 IF p_lease_seconds<10 OR p_lease_seconds>3600 THEN RAISE EXCEPTION 'Invalid crawl lease'; END IF;
 LOOP
 SELECT * INTO task FROM public.crawl_tasks
 WHERE (status='pending' AND next_fetch_at<=now()) OR (status='running' AND lease_until<=now())
 ORDER BY next_fetch_at,priority DESC,created_at,id FOR UPDATE SKIP LOCKED LIMIT 1;
 IF NOT FOUND THEN RETURN; END IF;
 IF task.status='running' THEN
  UPDATE public.crawl_runs SET status='expired',finished_at=now() WHERE lease_token=task.lease_token AND status='running';
 END IF;
 IF task.attempt>=task.max_attempts THEN
  UPDATE public.crawl_tasks SET status='dead',lease_token=NULL,lease_until=NULL,updated_at=now() WHERE id=task.id;
  CONTINUE;
 END IF;
 EXIT;
 END LOOP;
 token:=gen_random_uuid();
 UPDATE public.crawl_tasks SET status='running',attempt=attempt+1,lease_token=token,
 lease_until=now()+make_interval(secs=>p_lease_seconds),updated_at=now() WHERE id=task.id RETURNING * INTO task;
 INSERT INTO public.crawl_runs(task_id,lease_token,attempt) VALUES(task.id,token,task.attempt);
 RETURN NEXT task;
END $$;

CREATE FUNCTION public.renew_crawl(p_task_id uuid,p_token uuid,p_lease_seconds integer DEFAULT 120)
RETURNS boolean LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog,public AS $$
BEGIN
 IF p_lease_seconds<10 OR p_lease_seconds>3600 THEN RAISE EXCEPTION 'Invalid crawl lease'; END IF;
 UPDATE public.crawl_tasks SET lease_until=now()+make_interval(secs=>p_lease_seconds),updated_at=now()
 WHERE id=p_task_id AND lease_token=p_token AND status='running' AND lease_until>now();
 RETURN FOUND;
END $$;

CREATE FUNCTION public.finish_crawl(p_task_id uuid,p_token uuid,p_status text,p_result jsonb,p_retry_at timestamptz DEFAULT NULL)
RETURNS boolean LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog,public AS $$
DECLARE task public.crawl_tasks;
BEGIN
 IF p_status NOT IN ('complete','incomplete','blocked') THEN RAISE EXCEPTION 'Invalid crawl status'; END IF;
 SELECT * INTO task FROM public.crawl_tasks WHERE id=p_task_id AND lease_token=p_token
 AND status='running' AND lease_until>now() FOR UPDATE;
 IF NOT FOUND THEN RETURN false; END IF;
 UPDATE public.crawl_runs SET status=p_status,result=p_result,finished_at=now() WHERE lease_token=p_token;
 UPDATE public.crawl_tasks SET status=CASE WHEN p_status='complete' THEN 'complete'
 WHEN attempt>=max_attempts THEN 'dead' ELSE 'pending' END,
 next_fetch_at=coalesce(p_retry_at,now()+make_interval(secs=>least(86400,60*(2^least(attempt,10))::integer))),
 lease_token=NULL,lease_until=NULL,updated_at=now() WHERE id=p_task_id;
 RETURN true;
END $$;
REVOKE ALL ON FUNCTION public.enqueue_crawl(text,jsonb,integer,timestamptz),public.claim_crawl(integer),public.renew_crawl(uuid,uuid,integer),public.finish_crawl(uuid,uuid,text,jsonb,timestamptz) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_crawl(text,jsonb,integer,timestamptz),public.claim_crawl(integer),public.renew_crawl(uuid,uuid,integer),public.finish_crawl(uuid,uuid,text,jsonb,timestamptz) TO service_role;

CREATE OR REPLACE FUNCTION "public"."merge_duplicate_catalog_jobs"("p_keeper_id" bigint, "p_duplicate_ids" bigint[], "p_dedupe_key" "text") RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
DECLARE deleted_count integer;
BEGIN
  IF auth.role() <> 'service_role' THEN RAISE EXCEPTION 'Access denied'; END IF;
  IF p_keeper_id = ANY(p_duplicate_ids) OR cardinality(p_duplicate_ids) > 100
    OR p_dedupe_key IS NULL OR length(p_dedupe_key) > 500 THEN
    RAISE EXCEPTION 'Invalid duplicate merge request';
  END IF;
  -- A conflicting tracked state leaves both jobs intact for manual resolution.
  IF EXISTS (
    SELECT 1 FROM public.user_job_statuses a JOIN public.user_job_statuses b
      ON a.user_id=b.user_id AND a.job_id=p_keeper_id AND b.job_id=ANY(p_duplicate_ids)
    WHERE a.status IS DISTINCT FROM b.status
  ) OR EXISTS (
    SELECT 1 FROM public.user_job_statuses a JOIN public.user_job_statuses b
      ON a.user_id=b.user_id AND a.job_id=ANY(p_duplicate_ids) AND b.job_id=ANY(p_duplicate_ids)
      AND a.job_id <> b.job_id AND a.status IS DISTINCT FROM b.status
  ) THEN RETURN 0; END IF;
  INSERT INTO public.user_job_statuses(user_id,job_id,status,updated_at,is_saved)
  SELECT user_id,p_keeper_id,status,max(updated_at),bool_or(is_saved) FROM public.user_job_statuses
  WHERE job_id=ANY(p_duplicate_ids) GROUP BY user_id,status
  ON CONFLICT (user_id,job_id) DO UPDATE SET is_saved=public.user_job_statuses.is_saved OR excluded.is_saved;
  INSERT INTO public.user_job_evaluations(user_id,job_id,relevance,fit_tier,matched_skills,
    ai_analysis,calculated_at,scoring_job_hash,scoring_profile_hash,scoring_version)
  SELECT user_id,p_keeper_id,relevance,fit_tier,matched_skills,ai_analysis,calculated_at,
    scoring_job_hash,scoring_profile_hash,scoring_version
  FROM public.user_job_evaluations WHERE job_id=ANY(p_duplicate_ids)
  ON CONFLICT (user_id,job_id) DO NOTHING;
  UPDATE public.job_occurrences SET job_id=p_keeper_id WHERE job_id=ANY(p_duplicate_ids);
  DELETE FROM public.jobs WHERE id=ANY(p_duplicate_ids);
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  UPDATE public.jobs SET dedupe_key=p_dedupe_key WHERE id=p_keeper_id;
  RETURN deleted_count;
END;
$$;



-- Lease validation, catalog facts and source observations commit together.
CREATE FUNCTION public.persist_crawl_jobs(p_task_id uuid,p_token uuid,p_jobs jsonb)
RETURNS SETOF public.jobs LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog,public AS $$
DECLARE task public.crawl_tasks; item jsonb; vacancy public.jobs; saved public.jobs;
BEGIN
 SELECT * INTO task FROM public.crawl_tasks WHERE id=p_task_id AND lease_token=p_token
 AND status='running' AND lease_until>now() FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Crawl lease expired'; END IF;
 IF jsonb_typeof(p_jobs)<>'array' OR jsonb_array_length(p_jobs)>50 OR octet_length(p_jobs::text)>4194304 THEN
  RAISE EXCEPTION 'Invalid crawl batch';
 END IF;
 FOR item IN SELECT value FROM jsonb_array_elements(p_jobs) LOOP
  vacancy:=jsonb_populate_record(NULL::public.jobs,item->'job');
  INSERT INTO public.jobs(dedupe_key,title,company,location,employment_type,salary_text,description,url,source,
   employer_id,latitude,longitude,coordinate_source,last_seen_at,closed_at)
  VALUES(vacancy.dedupe_key,vacancy.title,vacancy.company,vacancy.location,vacancy.employment_type,
   vacancy.salary_text,vacancy.description,vacancy.url,vacancy.source,vacancy.employer_id,vacancy.latitude,
   vacancy.longitude,vacancy.coordinate_source,now(),NULL)
  ON CONFLICT(dedupe_key) DO UPDATE SET title=excluded.title,company=excluded.company,location=excluded.location,
   employment_type=excluded.employment_type,salary_text=excluded.salary_text,description=excluded.description,
   url=excluded.url,source=excluded.source,employer_id=coalesce(excluded.employer_id,jobs.employer_id),
   latitude=excluded.latitude,longitude=excluded.longitude,coordinate_source=excluded.coordinate_source,
   last_seen_at=now(),closed_at=NULL RETURNING * INTO saved;
  INSERT INTO public.job_occurrences(job_id,source_key,external_id,source_url,content_hash)
  VALUES(saved.id,task.source_key,item->>'external_id',saved.url,item->>'content_hash')
  ON CONFLICT(source_key,external_id) DO UPDATE SET job_id=excluded.job_id,source_url=excluded.source_url,
   content_hash=excluded.content_hash,last_seen_at=now();
  RETURN NEXT saved;
 END LOOP;
END $$;
REVOKE ALL ON FUNCTION public.persist_crawl_jobs(uuid,uuid,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.persist_crawl_jobs(uuid,uuid,jsonb) TO service_role;
