-- NextGig Supabase Unified Schema
-- Run this script in your Supabase SQL Editor (Dashboard -> SQL Editor -> New Query)

-- ==============================================================================
-- 1. JOBS TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    location TEXT NOT NULL DEFAULT 'Not specified',
    employment_type TEXT NOT NULL DEFAULT 'Not specified',
    salary_text TEXT,
    description TEXT NOT NULL,
    url TEXT NOT NULL,
    source TEXT NOT NULL,
    relevance INTEGER NOT NULL DEFAULT 0,
    matched_skills JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL DEFAULT 'new',
    first_seen_at TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ DEFAULT NOW(),
    fit_tier TEXT DEFAULT 'Unassessed',
    role_domain TEXT DEFAULT 'General',
    seniority_level TEXT DEFAULT 'Not specified',
    ai_analysis JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_jobs_status ON public.jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_relevance ON public.jobs(relevance DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_domain ON public.jobs(role_domain);
CREATE INDEX IF NOT EXISTS idx_jobs_company ON public.jobs(company);

-- ==============================================================================
-- 2. SOURCES TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    url TEXT NOT NULL,
    mode TEXT NOT NULL DEFAULT 'company crawler',
    last_status TEXT NOT NULL DEFAULT 'Not synced',
    last_synced_at TIMESTAMPTZ,
    detail TEXT,
    vacancies_found INTEGER DEFAULT 0
);

-- ==============================================================================
-- 3. EMPLOYERS TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.employers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    sector TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 1,
    careers_url TEXT NOT NULL,
    discovered_jobs_url TEXT,
    last_scraped_at TIMESTAMPTZ,
    status TEXT DEFAULT 'pending',
    vacancies_found INTEGER DEFAULT 0
);

-- ==============================================================================
-- 4. AUTHORIZED USERS TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.authorized_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial authorized admin email(s) (update with your allowed Google login email)
INSERT INTO public.authorized_users (email, role)
VALUES
    ('admin@example.com', 'admin')
ON CONFLICT (email) DO NOTHING;

-- ==============================================================================
-- 5. USER-SPECIFIC JOB STATUSES TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_job_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'new',
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_email, job_id)
);

CREATE INDEX IF NOT EXISTS idx_user_job_statuses_user_email ON public.user_job_statuses(user_email);
CREATE INDEX IF NOT EXISTS idx_user_job_statuses_job_id ON public.user_job_statuses(job_id);

-- ==============================================================================
-- 6. USER PROFILES TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL DEFAULT '',
    headline TEXT NOT NULL DEFAULT '',
    "current_role" TEXT NOT NULL DEFAULT '',
    location TEXT NOT NULL DEFAULT '',
    minimum_salary INTEGER NOT NULL DEFAULT 50000,
    employment TEXT NOT NULL DEFAULT 'Permanent only',
    education TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    keywords TEXT[] DEFAULT '{}',
    first_name TEXT DEFAULT '',
    last_name TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    phone_country_code TEXT DEFAULT '+353',
    linkedin_url TEXT DEFAULT '',
    work_authorization TEXT DEFAULT 'EU Citizen',
    gender TEXT DEFAULT '',
    current_company TEXT DEFAULT '',
    years_of_experience TEXT DEFAULT '10+ years',
    target_roles TEXT[] DEFAULT '{}',
    target_locations TEXT[] DEFAULT '{}',
    work_mode TEXT DEFAULT 'Hybrid',
    work_modes TEXT[] DEFAULT '{Hybrid,Remote,On-site}',
    salary_min INTEGER DEFAULT 50000,
    highest_education TEXT DEFAULT 'Master''s Degree (QQI Level 9)',
    education_details TEXT DEFAULT '',
    languages TEXT[] DEFAULT '{}',
    tools_software TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_profiles_user_email ON public.user_profiles(user_email);

-- ==============================================================================
-- 7. USER CV STORAGE TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_cvs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL UNIQUE,
    file_name TEXT NOT NULL,
    file_size INTEGER NOT NULL DEFAULT 0,
    mime_type TEXT NOT NULL DEFAULT 'application/pdf',
    file_data TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_cvs_user_email ON public.user_cvs(user_email);

-- ==============================================================================
-- 8. ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
-- Strict Security Model:
--   * Anonymous (anon): ZERO access to any table.
--   * Authenticated uninvited users: CANNOT read jobs, sources, employers, or other profiles.
--   * Authenticated authorized users:
--       - Read-only access to shared jobs, sources, employers.
--       - STRICT isolation: Can ONLY read, insert, update, or delete their OWN profile, CV, and job statuses.
--       - Cannot query or see other users' emails or records in authorized_users.
--   * Backend Scraper (service_role): Bypasses RLS to insert/update jobs and employers.
-- ==============================================================================

ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.authorized_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_job_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_cvs ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- Purge ALL existing policies on these tables (regardless of what name they have)
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    pol RECORD;
BEGIN
    FOR pol IN
        SELECT schemaname, tablename, policyname
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename IN ('jobs', 'sources', 'employers', 'authorized_users', 'user_job_statuses', 'user_profiles', 'user_cvs')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', pol.policyname, pol.schemaname, pol.tablename);
    END LOOP;
END $$;

-- -----------------------------------------------------------------------------
-- Helper Function: Check if the authenticated caller is in authorized_users
-- Runs with SECURITY DEFINER to avoid circular RLS recursion.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_authorized_user()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.authorized_users
    WHERE lower(email) = lower(auth.jwt() ->> 'email')
  );
$$;

-- -----------------------------------------------------------------------------
-- 8.1 AUTHORIZED USERS
-- Users can ONLY check if THEIR OWN email is authorized.
-- Prevents any user from enumerating or viewing other allowed users.
-- -----------------------------------------------------------------------------
CREATE POLICY "Users can only check own authorization"
  ON public.authorized_users FOR SELECT
  TO authenticated
  USING (lower(email) = lower(auth.jwt() ->> 'email'));

-- -----------------------------------------------------------------------------
-- 8.2 JOBS
-- ONLY verified authorized users can read jobs.
-- No public/anon access. Writes handled exclusively by backend service_role.
-- -----------------------------------------------------------------------------

CREATE POLICY "Authorized users can read jobs"
  ON public.jobs FOR SELECT
  TO authenticated
  USING (public.is_authorized_user());

-- -----------------------------------------------------------------------------
-- 8.3 SOURCES
-- ONLY verified authorized users can read sources.
-- -----------------------------------------------------------------------------
CREATE POLICY "Authorized users can read sources"
  ON public.sources FOR SELECT
  TO authenticated
  USING (public.is_authorized_user());

-- -----------------------------------------------------------------------------
-- 8.4 EMPLOYERS
-- ONLY verified authorized users can read employers.
-- -----------------------------------------------------------------------------
CREATE POLICY "Authorized users can read employers"
  ON public.employers FOR SELECT
  TO authenticated
  USING (public.is_authorized_user());

-- -----------------------------------------------------------------------------
-- 8.5 USER JOB STATUSES
-- Strict personal isolation: Users can ONLY read and write their OWN status rows.
-- -----------------------------------------------------------------------------
CREATE POLICY "Users read own statuses"
  ON public.user_job_statuses FOR SELECT
  TO authenticated
  USING (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'));

CREATE POLICY "Users insert own statuses"
  ON public.user_job_statuses FOR INSERT
  TO authenticated
  WITH CHECK (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'));

CREATE POLICY "Users update own statuses"
  ON public.user_job_statuses FOR UPDATE
  TO authenticated
  USING (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'))
  WITH CHECK (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'));

-- -----------------------------------------------------------------------------
-- 8.6 USER PROFILES
-- Strict personal isolation: Users can ONLY read and write their OWN profile.
-- Other users' profiles, personal details, and career summaries are inaccessible.
-- -----------------------------------------------------------------------------
CREATE POLICY "Users read own profile"
  ON public.user_profiles FOR SELECT
  TO authenticated
  USING (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'));

CREATE POLICY "Users insert own profile"
  ON public.user_profiles FOR INSERT
  TO authenticated
  WITH CHECK (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'));

CREATE POLICY "Users update own profile"
  ON public.user_profiles FOR UPDATE
  TO authenticated
  USING (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'))
  WITH CHECK (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'));

-- -----------------------------------------------------------------------------
-- 8.7 USER CVs (Resume Documents)
-- Strict personal isolation: Users can ONLY read, upload, update, or delete their OWN CV.
-- Other users cannot view or download anyone else's resume.
-- -----------------------------------------------------------------------------
CREATE POLICY "Users read own cv"
  ON public.user_cvs FOR SELECT
  TO authenticated
  USING (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'));

CREATE POLICY "Users insert own cv"
  ON public.user_cvs FOR INSERT
  TO authenticated
  WITH CHECK (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'));

CREATE POLICY "Users update own cv"
  ON public.user_cvs FOR UPDATE
  TO authenticated
  USING (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'))
  WITH CHECK (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'));

CREATE POLICY "Users delete own cv"
  ON public.user_cvs FOR DELETE
  TO authenticated
  USING (public.is_authorized_user() AND lower(user_email) = lower(auth.jwt() ->> 'email'));

-- ==============================================================================
-- 9. REALTIME CONFIGURATION
-- ==============================================================================
-- Add tables to the supabase_realtime publication so database changes propagate
-- to connected clients across multiple devices.
ALTER PUBLICATION supabase_realtime ADD TABLE public.jobs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.user_job_statuses;
ALTER PUBLICATION supabase_realtime ADD TABLE public.sources;
ALTER PUBLICATION supabase_realtime ADD TABLE public.employers;
ALTER PUBLICATION supabase_realtime ADD TABLE public.user_profiles;

-- Ensure replica identity is set to FULL so UPDATE and DELETE events broadcast full row data
ALTER TABLE public.jobs REPLICA IDENTITY FULL;
ALTER TABLE public.user_job_statuses REPLICA IDENTITY FULL;
ALTER TABLE public.sources REPLICA IDENTITY FULL;
ALTER TABLE public.employers REPLICA IDENTITY FULL;
ALTER TABLE public.user_profiles REPLICA IDENTITY FULL;

